CREATE DATABASE menu;
\c menu

CREATE TABLE COMIDA (
    IDCOMIDA serial  NOT NULL,
    NOMBREC varchar(100)  NOT NULL,
    CATEGORIA varchar(100) NOT NULL,
    ESTADO char(1) NOT NULL DEFAULT 'A' CHECK (ESTADO IN ('A','I')),
    CONSTRAINT COMIDA_pk PRIMARY KEY (IDCOMIDA)
);

CREATE TABLE MENU (
    IDPMENU serial NOT NULL,
    NOMBREM varchar(100) NOT NULL,
    CONSTRAINT MENU_pk PRIMARY KEY (IDPMENU)
);

CREATE TABLE MENU_DETALLE (
    IDMENUDETALLE serial  NOT NULL,
    IDCOMIDA int  NOT NULL,
    IDPMENU int  NOT NULL,
    CONSTRAINT MENU_DETALLE_pk PRIMARY KEY (IDMENUDETALLE)
);

ALTER TABLE MENU_DETALLE ADD CONSTRAINT MENU_DETALLE_COMIDA
    FOREIGN KEY (IDCOMIDA)
    REFERENCES COMIDA (IDCOMIDA)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

ALTER TABLE MENU_DETALLE ADD CONSTRAINT MENU_DETALLE_MENU
    FOREIGN KEY (IDPMENU)
    REFERENCES MENU (IDPMENU)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;
